services:
  - type: web
    name: campspot-express-api
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8787
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false

    healthCheckPath: /
    autoDeploy: true